### ISSUE TITLE
Messaging Screen

### ISSUE THREAD

**Issue by the-lost-explorer** [VITCMUN/munverse#12]
## To-do
Make the messaging screen by following the **[prototype](https://drive.google.com/drive/folders/1-4rcCVZbM7W3cjmh_XpJVtAHVeGcNMbW?usp=sharing)** and **design standards**. 
Check wiki for design standards and follow them **very strictly**. 

### Files to play with:
-   munverse/media - images and icons go here under appropriate folders.
-   munverse/views/partials - Your .ejs files go here or one folder before.
-   munverse/public - Your css and js files go here under their separate folders.

**Comment by shubham1172** [comment]
Completed in #20.
