### ISSUE TITLE
Country icons

### ISSUE THREAD

**Issue by the-lost-explorer** [VITCMUN/munverse#17]
We need to get all the country icons - rounded and following the size as per the Design Standards. Required suggestions to get them.

**Comment by shubham1172** [comment]
[This](https://www.flaticon.com/packs/countrys-flags) can be used but their license demands an acknowledgement. I guess it'll do.

**Comment by dwij2812** [comment]
Apart from that we need the Council logo with the VITCMUN logo as shown in the messaging screen prototype to be placed on the center of the navbar
