### ISSUE TITLE
CircleCI icons crashing/failing to load when tests not passed.

### ISSUE THREAD

**Issue by the-lost-explorer** [VITCMUN/munverse#23]
**Description**
CircleCI icons crashing/failing to load when tests not passed.

**To Reproduce**
Check README when build fails.

**Expected behavior**
Icons visible with red color for build failed.

**Desktop:**
 - Browser [Chrome]

**Comment by shubham1172** [comment]
It's not CircleCI, it's the dependency badges. Reason being, the [server](https://github.com/alanshaw/david) which hosts them is down right now.

Let's wait another day for it to go live, we'll remove it otherwise.
